### ISSUE TITLE
Column menu's filter clear button throw's error in ej2 Grid

### ISSUE THREAD

**Issue by WASIT412** [syncfusion/ej2#13]
I am using typescript ej-grid with column menu and create custom template for filter. The clear filter button throw's error when used with column menu, but it is work proper without column menu functionality 
For more reference click on this link (http://plnkr.co/edit/GLDuR6ZYCPUA7TXivOlY?p=preview)

Below is my column menu.
![columnmenu](https://user-images.githubusercontent.com/10867761/34437900-8404f5ce-ecc8-11e7-902d-4d63540f36b8.PNG)

And below is error which i am getting when i pressing clear button.

![clearbtn](https://user-images.githubusercontent.com/10867761/34437968-f53b69d0-ecc8-11e7-9d16-00991d92426f.PNG)

,

**Comment by Pavithra15** [comment]
Hi WASIT412,

We have checked your query and we have considered “Filter menu Clear button throws script error with column menu” as a defect and logged a report for the same. The fix will be available in our January 10, 208 release. 

Regards, 
Pavithra S.

**Comment by RamdhasUeikattan** [comment]
Hi Wasit,

Thanks for your patience.

We are glad to announce that the Essential JS 2 Grid (v15.4.24) has been released. In this release, we have included the fix for “Filter menu Clear button throws script error with column menu” issue. 

Please let us know if you have any queries.

Regards,
Ramdhas  Ueikattan
