### ISSUE TITLE
scss theme files

### ISSUE THREAD

**Issue by hamdiwanis** [syncfusion/ej2#18]
hello, im tring to follow the documentaion on customizing the theme by importing the sass file like these
`@import "~@syncfusion/ej2-ng-calendars/styles/material.scss";`
but i getthe next build error
```
ERROR in ./src/modules/shared/components/data-range-selector/data-range-selector.component.scss
Module build failed: 
@import 'ej2-base/styles/material.scss';
^
      File to import not found or unreadable: ej2-base/styles/material.scss.
Parent style sheet: /project/node_modules/@syncfusion/ej2-ng-calendars/styles/calendar/material.scss
      in /project/node_modules/@syncfusion/ej2-ng-calendars/styles/calendar/material.scss (line 1, column 1)
Error: 
@import 'ej2-base/styles/material.scss';
^
      File to import not found or unreadable: ej2-base/styles/material.scss.
Parent style sheet: /Volumes/DATA/Work/logisfleet/taskme/lds-ngx/node_modules/@syncfusion/ej2-ng-calendars/styles/calendar/material.scss
      in /project/node_modules/@syncfusion/ej2-ng-calendars/styles/calendar/material.scss (line 1, column 1)
    at options.error (/project/lds-ngx/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/modules/shared/components/data-range-selector/data-range-selector.component.ts 71:21-68
 @ ./src/modules/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

```

im using ej2-ng-calendar with angualr 5. thanks

**Comment by ThirukumanaranM** [comment]
Hi Hamdiwanis, 
 
Thanks for your interest in Essential JS 2. 
 
We have looked in to your query “While using @import "~@syncfusion/ej2-ng-calendars/styles/material.scss"; but I get the next build error” and we suspect the root cause of the issue (SCSS compilation) might be due to missing SCSS compiling configuration in your application. To overcome this please add the stylePreprocessorOptions option to the .angular-cli.json file.  
For your reference we have created the custom sample with SCSS compilation of Essential JavaScript 2 for Angular. 
 
Please find the below sample link. 
Link: https://github.com/SyncfusionSamples/ej2-angular-scss 
 
Steps to run the above sample: 
 
1.	Please download the application from the above link.
2.	Run “npm install” command from the root directory of your application.
3.	Run “npm install @syncfusion/ej2-ng-calendars --save” command to install Syncfusion Calendar packages.
4.	Run “npm install @angular-devkit/core” to install Angular devkit tool for compilation.
5.	Please make use of the below code example to render the Calendar component.
6.	Please import the Calendar module in app.module.ts file as like in the below code example.
```
[app.module.ts] 
import { NgModule }      from '@angular/core'; 
import { BrowserModule } from '@angular/platform-browser'; 
    // import the CalendarModule for the Calendar component 
import { CalendarModule } from '@syncfusion/ej2-ng-calendars'; 
import { AppComponent }  from './app.component'; 
 
@NgModule({ 
    //declaration of ej2-ng-calendars module into NgModule 
    imports:      [ BrowserModule, CalendarModule ], 
    declarations: [ AppComponent ], 
    bootstrap:    [ AppComponent ] 
}) 
export class AppModule { } 
```
```
 
[app.component.html] 

<ej-calendar></ej-calendar> 
```
 
7.	Then Run “npm start” command to launch the application.
 
If you are still facing any issue. kindly revert us with more details that will be helpful to provide the exact solution.

**Comment by hamdiwanis** [comment]
thanks for your help, this what was missing in anguler-cli config if anyone else have the same problem 
```
"stylePreprocessorOptions": {
            "includePaths": [
                "../node_modules/@syncfusion"
            ]
        },
```

**Comment by getsetbro** [comment]
What is needed when working with React?
