### ISSUE TITLE
Remove builtin Font and Icon

### ISSUE THREAD

**Issue by auvansang** [syncfusion/ej2#24]
As developer, I want to use a custom font and external icon such as Font awesome, Material icon.
However, I see ej2 used builtin Roboto Font and ej-icons. This is the reason why the css file is large.
By removing all builtin, this will reduces the package size, and allow developer uses any icon for all components.

**Comment by ajithr** [comment]
Hi @auvansang , 

Thanks for your interest in Essential JS 2.

We have planned to split-up the built-in icons and icon customization using SVG instead of font icons in our Essential Studio Volume 2, 2018 release wish list which will be tentatively available by May 2018. Once the icon split up and icon customization has been achieved, the package size will get reduced. 

Please let us know if you have any concerns. 

Regards, 
Ajith R

**Comment by bharathm03** [comment]
I'm closing this issue as there is no recent updates here.

**Comment by RobbinBaauw** [comment]
Hi @ajithr,

I'm using Angular 6, and I would like to use FontAwesome as well.

But FontAwesome has released their Angular package for FA (https://github.com/FortAwesome/angular-fontawesome), and I would like to use this way of using components instead of the class way. This provides an advantage, namely Tree Shaking and being able to dynamically change an icon.

I have not found a way to use this in combination with EssentialJS2 though, as it's all class based. Is there a way to solve this? This would improve the usability of icons a lot.

Thanks in advance.
