### ISSUE TITLE
React TreeView display bugs on second render

### ISSUE THREAD

**Issue by louisptremblay** [syncfusion/ej2#27]
Easy to reproduce:
https://stackblitz.com/edit/syncfusion-treeview-refresh-bug?file=index.tsx

- Click "Change container state"

Unexpected behaviors:
- Drag & drop has duplicate labels
- Expand animation is played for the whole tree on every render

![syncfusion_treeview_bug2](https://user-images.githubusercontent.com/779615/40988919-580135a0-68ba-11e8-9dbd-c937abcb9b1f.gif)
![syncfusion_treeview_bug1](https://user-images.githubusercontent.com/779615/40988920-5817d5da-68ba-11e8-9c20-d1d0081a70ee.gif)

Thank you

**Comment by AshokkumarBalasubramanian** [comment]
Hi @louisptremblay ,

We have analyzed your problem with your provided sample. From that sample, you have tried to change the value for a label element under App component using setState functionality, where our TreeView control also placed in the same component. 

When we change a state of an component it re-renders the whole component so that the TreeView also getting re-rendered. So, we suggest you to split the code blocks into different components, so that the change from one component won’t affect another one.

We have modified your provided sample. Please check it in below link.

https://stackblitz.com/edit/syncfusion-treeview-refresh-bug-8wstvw?file=initial.tsx

Please let us know, if you have any concern on this.

Regards,
Ashokkumar B
(Syncfusion)

**Comment by louisptremblay** [comment]
Unfortunately, that workaround would essentially make the tree readonly.

Anytime the tree data changes, you *do* need to render the tree again, and the bug will appear.

Here is another example that might be clearer. When pressing the button, it changes the tree data and refreshes, and we get the duplicate labels:

https://stackblitz.com/edit/syncfusion-treeview-refresh-bug-joxxrr?file=index.tsx

**Comment by AshokkumarBalasubramanian** [comment]
Hi @louisptremblay ,

We were able to reproduce your reported problem (“Dragged element having duplicate labels in TreeView component”) at our end. We have confirmed this as a bug and logged the bug report for this. We will fix and include the fix on our upcoming Vol 2, SP1 2018 release.

Regards,
Ashokkumar B.

**Comment by AshokkumarBalasubramanian** [comment]
Hi @louisptremblay ,

We have fixed your reported problem, TreeView component redrawn and duplicate label added when change the states in React. The fix is included on our updated ej2-react-base (16.1.48) package. Please check the below sample and updated package details are available in below link, please find it.

Updated Sample: https://stackblitz.com/edit/syncfusion-treeview-refresh-bug-m5yjhw?file=SubComponentWithTreeView.tsx
 
Package Reference: https://www.npmjs.com/package/@syncfusion/ej2-react-base/v/16.1.48

Please let us know, if you have any concern on this.

Regards,
Ashokkumar B.
(Syncfusion)

**Comment by louisptremblay** [comment]
I confirm it is now fixed
Thank you!
