### ISSUE TITLE
Grid column autohide

### ISSUE THREAD

**Issue by krosoftware** [syncfusion/ej2#3]
Hello
is there option to "autohide" column when displaying on mobile device?
For example, if client is desktop, displayed are 6 grid columns and on iPad displayed are only 4 columns and on iPhone only 2 columns.
Thank you.

**Comment by RamdhasUeikattan** [comment]
Hi KroSoftware,

Thanks for using Syncfusion products.

We have analyzed your requirement for “Grid columns priority support for Auto hide”. As this feature is not available in our product, we will consider this a feature request. If you could confirm some specific details, it would help us to implement the feature in line with your requirement.

Please review the following description of the feature and let us know if it conforms to your requirement.

"Support for Grid columns priority for auto hiding the columns based on device screen size"

If our definition of this feature is different from your requirement, then let us know the specific details, so that we can work towards fulfilling your requirement.

Regards,
Ramdhas U.

**Comment by krosoftware** [comment]
Hello Ramdhas
thank you for consideration.
Yes, that's what I meant and here is additional description - as you decided to have one framework for desktop and phones (which is great btw.) then I think it will be great option to have something like this:
http://demos.jquerymobile.com/1.4.5/table-column-toggle/
where you can define column priority - which means, columns are displayed on devices based on defined priority and device screen size.
Thank you again.

**Comment by bharathm03** [comment]
@krosoftware Thank you for your help in defining this feature. We have increased priority for this feature. This will be available in our upcoming main release which is expected to be rolled out at end of July. 

Please let me know if you have any concerns.

Thanks
Bharath

**Comment by krosoftware** [comment]
Thank you, you are very kind. 👍

**Comment by RamdhasUeikattan** [comment]
@krosoftware We are glad to announce that our Essential JS 2 release v1.0.17 is rolled out and the column chooser feature was included in this release. Please find the below sample link for your reference.

sample link:  http://ej2.syncfusion.com/demos/index.html#/material/grid/columnchooser.html 

Regards,
Ramdhas U.

**Comment by krosoftware** [comment]
Awesome, thank you.
